name: deploy-server
on:
  push:
    branches:
    - main
    paths:
    - server/**
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
      run: go build -o bin/app
    - uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run:
        cd server
        docker build . -t yapl/yapl-playground:latest
        docker push yapl/yapl-playground:latest
        