name: deploy-server
on:
  push:
    branches:
    - main
    paths:
    - server/**
    - .github/**
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build & Push
      run: |
        cd server
        go build -o app
        docker build . -t ahsayde/yapl-playground:latest
        docker push ahsayde/yapl-playground:latest
